---
title: "command_line_interface"
author: "Pamgene Support"
date: "6/19/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
A user requirement for a pamservice tool to be used with 

* exising ps12 instruments
* new ps12 instruments

The requirements cover the command line.

## differences with the pamstation types

* new ps12 has one control board less (no wash board)
* new ps12 has an integrated barcode reader
* new ps12 has one dispense needle

## command line
A command line interface to the pamstation12



## stage commands

`home x y`

`load x y`

`x +20`

`x -20`

`home`

`x home`

`y home`

`enable all boards`

`read xy parameters`

`home`

`load`

`read`

`aspirate`

`dispense`

`frontpanel`

`incubate`

`get and set xyparameters`

`get all xyparameters`

## camera commands

`go read`

`get image`

look at image

change xy positon

`flash( set )`

...repeat

## valves commands

`open all valves`

`close all valves`

`close valve 1 2 3 4` 

`read all values`

`pump up`

`pump down`

`pump valve 1 2 3 4` ( all other valves should be closed ) 


`underpressure ( pump )  -0.2`

`overpressure ( pump ) 0.2`

## aspirate commands

`aspirate` ( value next to it )

`needle up / down`

## disposable commands

`temp position 1 / 2 / 3`

`temp overall`

`temp cover 1 2 3`

`temp bottom 1 2 3`

## dispense commands

`Dispense 20ul`

default pos 2

### service tasks (use cases)
The field engineer performs the following service task

*  check valve leaks
*  check chip leaks
*  check dispensing system
*  check aspiration system
*  check temperature system
*  check optics
*  focussing the camera
*  replace sensor

#### check valve leaks

#### check chip leaks

#### check dispensing system

#### check aspiration system

#### check temperature system

#### check optics

#### focussing the camera

#### replace sensor




