---
title: "command_line_interface"
author: "Pamgene Support"
date: "6/19/2019"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction
A user requirement for a pamservice tool to be used with 

* exising ps12 instruments
* new ps12 instruments

The requirements cover the command line and the graphical user interface (GUI).

## differences with the pamstation types

* new ps12 has one control board less (no wash board)
* new ps12 has an integrated barcode reader
* new ps12 has one dispense needle

## command line
A command line interface to the pamstation12

### service tasks (use cases)
The field engineer performs the following service task

* check for leaks
* setting the wagon position
* focussing the camera
* calibration of sensors

#### check for leaks

#### setting the wagon position

#### focussing the camera

#### calibration of sensors

### stage commands

`home x y`

`load x y`

`x +20`

`x -20`

`home`

`x home`

`y home`

`enable all boards`

`read xy parameters`

`home`

`load`

`read`

`aspirate`

`dispense`

`frontpanel`

`incubate`

`get and set xyparameters`

`get all xyparameters`

### camera commands

`go read`

`get image`

look at image

change xy positon

`flash( set )`

...repeat

### valves commands

`open all valves`

`close all valves`

`close valve 1 2 3 4` 

`read all values`

`pump up`

`pump down`

`pump valve 1 2 3 4` ( all other valves should be closed ) 


`underpressure ( pump )  -0.2`

`overpressure ( pump ) 0.2`

### aspirate commands

`aspirate` ( value next to it )

`needle up / down`

### disposable commands

`temp position 1 / 2 / 3`

`temp overall`

`temp cover 1 2 3`

`temp bottom 1 2 3`

### dispense commands

`Dispense 20ul`

default pos 2



## Graphical User Interface
The requirements for a the GUI is outlined below and each tab is dealt with in each section.

### main tab
used to decide which board to connect

### parameters tab
used to see the flashed values of the parameters

### disposable tab
used to have livefeed of the disposable parameters

### pumping tab
used to have livefeed of the pumping parameters

### position tab
used to have livefeed of the 

### camera tab
not used
used to control the camera

### dispense tab
used to have a livefeed of the dispense

### input/outputs tab

used to get and set

* iccb (incubate board)
* sycb (system board)
* wsb (wash board)

### error tab
not used



